# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kanghee Cho
title: Bioinformatician
email: | 
  kh22cho@gmail.com / kh22cho@soongsil.ac.kr
website: https://kh22cho.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  kh22cho
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: 
linkedin_username: kh22cho
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Kanghee Cho, a master's student in Department of Bioinformatics at Soongsil University. I am passionate about data-driven biology, especially in the areas of single-cell transcriptomics, gene regulatory networks, and computational method development.

  I enjoy working with <mark>Python</mark>, <mark>R</mark>, and <mark>Linux</mark>-based environments. I'm experienced in handling large-scale biological datasets and have managed lab server systems for over 2 years to support collaborative research.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Soongsil University
        caption: Mar. 2021 - Aug. 2026 (expected)
        sub_title: Integrated B.S./M.S. in Life Science and Bioinformatics
        quote: >
          Founded in 1897, Soongsil University is Korea's first modern university and has played a pioneering role in the development of education, science, and technology in Korea.
        description: | # this will include new lines to allow paragraphs
          At Soongsil University, I am currently pursuing an Integrated B.S./M.S. program in Life Science and Bioinformatics. The program combines interdisciplinary training in molecular biology, computer science, and statistics, with a focus on data-driven biomedical research.

          During my undergraduate years, I served as the **vice president of the Student Council** in the Department of Chemistry, which helped me develop leadership and collaboration skills. Driven by my interest in data-driven biology, I joined a Laboratory for Single Cell Systems under the supervision of <strong>Professor Junil Kim</strong> [Homepage](https://sites.google.com/site/neocaleb/laboratory-for-single-cell-systems), where I contributed to projects involving scRNA-seq analysis.
          
          Currently, my master's research focuses on developing a computational tool for detecting multiplets in scRNA-seq data using latent Dirichlet allocation (LDA).
    
  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: Laboratory for Single Cell Systems
        caption: Sept. 2023 - Present
        sub_title: Research Assistant under Prof. Junil Kim
        description: |
          - Conducting research on gene regulatory network (GRN) controllability using developmental scRNA-seq data from zebrafish; manuscript in preparation.
          - Developing a computational tool to detect multiplets in scRNA-seq data and infer cell type combinations using LDA (latent Dirichlet allocation).
          - Contributed to the Deepdoublet project by designing simulation pipelines and performing benchmarking analysis (Genomics & Informatics, 2024).
          - Managed Linux server environments for collaborative research.

  - title: Publications
    layout: text
    content:  |
      <sub>*: Co-first author, †: Corresponding author</sub>

      Linbu Liao, Junyoung Kim, <strong>Kanghee Cho</strong>, Junil Kim, Byung-Kwan Lim<sup>†</sup>, Kyoung Jae Won<sup>†</sup>.
      DeepDoublet identifies neighboring cell dependent gene expression. <em>Genomics & Informatics</em>. 22, 30 (2024). [Link](https://doi.org/10.1186/s44342-024-00031-2)
      
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of my academic and research work, I enjoy activities that keep me curious and balanced.

      - Jogging and Running along the riverside
      - Brewing coffee and exploring several beans  
      - Trying out new recipes and enjoying delicious food
      - Traveling and discovering new places
      
      Here's a peaceful scene I encountered during one of my trips —  
      a quiet temple deep in the forest with a gentle sign that reads  
      <em>그대 발길 돌리는 곳 (A place where your footsteps pause).</em>

      <p align="center">
        <img src="/images/temple_sign.jpeg" alt="Temple scene" title="그대 발길 돌리는 곳"
          style="width: 300px; max-width: 100%; height: auto; border-radius: 8px;" />
      </p>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
